apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shadowsocks

resources:
- namespace.yaml
- daemonset.yaml
- service.yaml
- password-sealed.yaml

configMapGenerator:
- name: config
  files:
  - config.json
  options:
    disableNameSuffixHash: true
