apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: password
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  data:
  - secretKey: PASSWORD
    remoteRef:
      key: shadowsocks-password
