apiVersion: v1
kind: Service
metadata:
  name: shadowsocks
spec:
  type: NodePort
  selector:
    app: shadowsocks
  ports:
  - name: ss-tcp
    protocol: TCP
    port: 8388
    nodePort: 32388
  - name: ss-udp
    protocol: UDP
    port: 8388
    nodePort: 32388
