apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-auth
  namespace: flux-system
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    template:
      data:
        issuerURL: https://login.microsoftonline.com/{{ .tenant_id }}/v2.0
        clientID: "{{ .client_id }}"
  dataFrom:
  - extract:
      key: azure-ad-client-credentials
