apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube.ku1.uk
spec:
  secretName: kube.ku1.uk
  dnsNames:
  - kube.ku1.uk
  - "*.kube.ku1.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
