apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy

resources:
- namespace.yaml
- source.yaml
- release.yaml
- certificate.yaml
- ingressroute.yaml
- secret-sealed.yaml
- middleware/auth-headers.yaml
- middleware/oauth-claims.yaml
- middleware/oauth-token.yaml

configMapGenerator:
- name: values
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
