apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    template:
      data:
        oidc-issuer-url: https://login.microsoftonline.com/{{ .tenant_id }}/v2.0
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
        cookie-secret: "{{ .cookie_secret }}"
  data:
  - secretKey: cookie_secret
    remoteRef:
      key: oauth2-proxy-cookie-secret
  dataFrom:
  - extract:
      key: azure-ad-client-credentials
