config:
  existingSecret: oauth2-proxy
  existingConfig: oauth2-proxy
extraEnv:
- name: OAUTH2_PROXY_OIDC_ISSUER_URL
  valueFrom:
    secretKeyRef:
      name:  oauth2-proxy
      key: oidc-issuer-url
sessionStorage:
  type: redis
redis:
  enabled: true
  image:
    repository: redis
    tag: latest
  architecture: standalone
  master:
    persistence:
      size: 128Mi
