apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgAzGKtIJrsDpxAwoWjHl0CBWf0/dKwyOsa8enZKhlejc/BobsNVFkAv4ezDhQLEDcheX2hDM+88f8cegBvJSPXp0jdBwxy0zrbNY79+XghBnckVPDFfr6lCINCWi0kj2ucoTwpGn1bq81uRXFTIpvGWredshsqLx9xuolmdrt4/oxPsV1UETCbsk4WnPoplowpPDzEcz5Z86n9c7ms4/9Jo4MgYQvsEgzmAmWqP5o+sEFxK0tH9jLd0WWkyCTagXD9vhRVsbWEvhbVpLkB8sxXQdB9Xz9wFhDE0Fhajytp6GoFYYqh8PnyghtDyBQBep7I8KmGzXAjXtZWBM4be2UexazBJBm4fDJi/cnlHOTjvF4fozetyEM54stDe4t76qWSwBb/i/in5fS0pnG5ENxXEnsy/Bq6hZbkXn3EIiJQUuF+Nvq6bNJDxGTUyu7dJijzkPbCwK1Y/C4ypvNjtYEQ0/fjSc4AlXmhEzvnVOTj+ugvzLk27AH5zkeQCaMFyKMBN6GXnzUpdcTUvNBdbzcM3tAF8w+fF5GeLNu+JbHASTpj6GNZBL76bHR2plR8a8MEHMYAlESN1/Ck+8AVMhy543ATjxrtv9OS9U2oh+pmaWuuENWBQapoUwydVD/LqiB35pbyk/cw8TRLTjiL7lYnqJo7ERfv/6IBevF+rwf5AvrX702jBLrdVC3NG2Y6tajSJWz8NS9W5139H1Q/vvlVY0pGisfZgiv3B8IorcDux6QkDIFRa8mQCSqm3Wa55Ncjv0S+0NAchFuXKAVA=
    username: AgAFsto0503ylLFmuKeJdgtlOyWMJfcBmQKqLqq88R085MNZbDly1rsacZOhwySv+bo3xXPHupDo7i86MwhoNZcrdauS2/XGXUT3fo8EAAW9yQNcT82BjtLwWpGRFVUy8m5UDygS22m0rmDC2pj/pZlVHoIMaIo3VM3ZKWiJe8cK7moe9aCaG6+HYlxfR+n1il5PXnvWx0NSECvG1BEMjZ7lJys9ZCj4ZKSXlG9F0WjKYjfTiKLMHTB5DXaTGdoaYFYnOaTImBFtnN286x+9gN0FMDLA2ernIsQL7fP56xcNxepagpjPMv8O7zr13w451MASx//UuV712FKJYmRkUwwR771ipzh3AOhbix8vQTzZb1LqtcbcbdMe46dizDavdVSMsT11pu/PY6AjT9+zhDMKMIqZY0O0+2tm1T8oTfGJK7Lsi5jHXVJthRIhX2oq28rPbzBYgsyLFFZI12oIAogE5Fq3nCzcMKFeOT4+Uiss3qU/vyRy2r90ZpRGI6JbiRSJInq3Rke8lkvrKogrenhiXkm7gi1bsjOkLIVyMMLmh5AoTGiR3Li5dtVRH+P784my16k037S6LVbzkUUWet3n/PlROXeiVB5ueeh8tXV9kIHBDgBJFpR1a71jXcPrG8kwA5fgQpmALPSpNdSt+6q8RxGu6PH8BdfzQEaWCKk46AlRRVdwoc4mO6Sa+JTcnrMquq5r9g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system

