apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
  namespace: flux-system
stringData:
  issuerURL: https://login.microsoftonline.com/5dbfa540-5b23-4471-ad6a-c6d8ef02656d/v2.0
  clientID: 85470801-7f19-4cab-862f-7117bec77b92
