---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
  - name: metallb
  interval: 1h0m0s
  path: ./metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

