---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./config/native
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb
  healthChecks:
    - kind: DaemonSet
      name: speaker
      namespace: metallb-system
    - kind: Deployment
      name: controller
      namespace: metallb-system

