---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    semver: "*"
  url: https://github.com/metallb/metallb

