apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oracle-vault
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.ap-chuncheon-1.d5rvc5pmaahh6.ab4w4ljrvflipf7fiesbgyy2jqf7taesfmskaakhkwzs4kxovr7lco5xx2tq
      region: ap-chuncheon-1
