apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBXSE0o7PvygR2OYfvr1ponNzIgTYEdqKOUoQSDDi3S6jrFMnueQdDGCF+Fz/RWB2+ds1/ZTceGBi3OJLd1MITo8RU7973TgzNxpPbVdy9hBOWRT/MIhRZawiCLhniFmMhyRi6xs1oBwH0MMZSF1cSsEKESic+mc9DfRHF8RevIye6lKSYmiQax8f3cSUxgtwyVsbQSlW1H3UwrCsVzpA3fJAV8cfPOhYMqHPJml+giJSFJdVnqFyebkM/egouZGVDALGBk8picXdRrfMhxABNLS+BP7B4Uk2GfEjHyWI6wDfT1FEFQXlMkH5wwZgURT3BxCOIpKLyu6YMd5dT7qyg7eMhj05WWmlVkHyJoIIs7Fv8h6D/9hN6vdoAmGwxK6LOPeJwMG9oqJ1JC5muBo8oOV4USGopz+JIwruxDbV2FAUEeInRsVPrhENqvP7WJ1WBCfBRd1bc/79S/2YxownhWRhU2f+SfrwfQ4lWOiRP6YE07JIYTU4Gg+6Y2I6iKkwq+oALDi/lIdsGB33EZNbOaI2nAuoTUL9ntWDlaC+2OUz+i+P6ar/cpWGHYoR0dv8rkk1p1w4XlcWTBYy0ZSf0ZXjheXZzH9/br5Jj8JUuBKYZIA5jhQzfmjksSfLNIlo19nIzBCVHWY8I50aoyAAq7N3zpdHijsORWLYPoEJcAsW1Oi+i+oTw+U2516YAB9R4cubRqTaHyK8KU5Lww9pAZqfv1HwVra0slY6oOg7fy+EwSAQtYsixI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: traefik
    type: Opaque

