apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  additionalManifests:
  - URL: https://github.com/knative/net-certmanager/releases/latest/download/release.yaml
  ingress:
    contour:
      enabled: true
  config:
    domain:
      ku1.uk: ""
    network:
      ingress-class: contour.ingress.networking.knative.dev
      namespace-wildcard-cert-selector: |
        matchLabels:
          networking.knative.dev/enableWildcardCert: true
      auto-tls: Enabled
      http-protocol: Redirected
    certmanager:
      issuerRef: |
        kind: ClusterIssuer
        name: letsencrypt-cloudflare
