apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
- namespace.yaml
- source.yaml
- release.yaml
- traefik-api.yaml

configMapGenerator:
- name: values
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
