providers:
  kubernetesCRD:
    allowCrossNamespace: true
additionalArguments:
- --serverstransport.insecureskipverify=true
ports:
  web:
    redirectTo: websecure
service:
  ipFamilyPolicy: PreferDualStack
