providers:
  kubernetesCRD:
    allowCrossNamespace: true
additionalArguments:
- --serverstransport.insecureskipverify=true
ports:
  web:
    redirectTo: websecure
  websecure:
    http3:
      enabled: true
      advertisedPort: 443
service:
  ipFamilyPolicy: PreferDualStack
