---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: foundation
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./foundation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

