apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tele.ku1.uk
spec:
  secretName: tele.ku1.uk
  dnsNames:
  - tele.ku1.uk
  - "*.tele.ku1.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
