apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: tele.ku1.uk
spec:
  endpoints:
  - dnsName: tele.ku1.uk
    recordType: CNAME
    targets:
    - kube.ku1.uk
  - dnsName: "*.tele.ku1.uk"
    recordType: CNAME
    targets:
    - tele.ku1.uk
