apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport

resources:
- namespace.yaml
- source.yaml
- release.yaml
- service.yaml
- certificate.yaml
- ingressroute.yaml
- teleport-kube-agent-join-token.yaml

configMapGenerator:
- name: values
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
