---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  dependsOn:
  - name: kube-prometheus-stack
  interval: 1h0m0s
  path: ./loki-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

