apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-claims
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc/
    trustForwardHeader: true
    authResponseHeaders:
    - X-Auth-Request-User
    - X-Auth-Request-Groups
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
