apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/knative/serving/releases/latest/download/serving-core.yaml
- https://github.com/knative/net-kourier/releases/latest/download/kourier.yaml
- https://github.com/knative/net-certmanager/releases/latest/download/release.yaml
patchesStrategicMerge:
- config-network.yaml
- config-domain.yaml
- config-certmanager.yaml
