---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: metallb
  targetNamespace: metallb-system
  upgrade:
    crds: CreateReplace
  values:
    crds:
      validationFailurePolicy: Ignore # https://github.com/metallb/metallb/issues/1597

