---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport-kube-agent
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-kube-agent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: teleport
  interval: 1h0m0s
  releaseName: teleport-kube-agent
  valuesFrom:
  - kind: ConfigMap
    name: values

