apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/knative/net-contour/releases/latest/download/release.yaml
images:
- name: docker.io/envoyproxy/envoy
  newTag: v1.23-latest
patches:
- target:
    kind: Deployment
    name: contour
  patch: |
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--envoy-service-http-address=::"
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--envoy-service-https-address=::"
- target:
    kind: DaemonSet
    name: envoy
  patch: |
    - op: replace
      path: /kind
      value: Deployment
- target:
    kind: Service
    name: envoy
  patch: |
    - op: add
      path: /spec/ipFamilyPolicy
      value: PreferDualStack
